name: Close duplicate issues

on: [issues]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: spyder-ide/action-close-duplicate-issues@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          items: >-
            [
             {
               "pattern": "Add Selection Based support for Java",
               "reply": "Duplicate issue",
               "labels": ["resolution:Duplicate"],
               "close": true
             },
            ]
